### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hansputera** [hansputera/nonton-otakudesu#1]
## Todo List
- [x] Menambahkan slash command support.
```
Contoh slash command:
 1. /download https://otakudesu.lol/episode/...
 2. /cari@utekedesu_bot One piece
 3. /download@utekedesu_bot https://otakudesu.lol/episode/....
```
- [x] Bot mampu mengolah kembali pesan masa lalu apabila user mengedit pesan sebelumnya.
```
Contohnya:
---------------------
User (pesan baru) : /cari Boruto  (pesan A)
Bot (pesan baru): "Boruto (...)" (pesan B)

(setelah 5 detik atau beberapa lamanya)

User (edit pesan): /cari One Piece (pesan A)
Bot (edit pesan): "One Piece (...)" (pesan B)

--------------------------
Maksud disini ialah bot mampu menggunakan kembali pesan yang berlalu apabila user mengedit pesan sebelumnya juga. 
Untuk expiration time disini maksimal adalah 1 menit untuk mengurangi memory usage.
(I'll use file caching in next time)
```
- [x] Menambahkan button data caching (expiration time = 5 mins)
- [x] Menambahkan fitur query resolver (untuk resolve permintaan dengan username request)
```
Contohnya:
1. @utekdesu_bot cari one piece
2. @utekedesu_bot download https://otakudesu.lol/episode/...
```
- [x] Membuat commands handler
```
## Command Handler File Schema:

Arg# -> Object
Arg#name -> String
Arg#type -> Union(Option, Arg)
Arg#required -> Boolean

Command# -> Class
Command#name -> String
Command#aliases -> Array<String>
Command#args -> Array<Arg>
Command#flags -> Array<String>
Command#handle -> AsyncFunction(m -> [@structures/Message.js:MessageEvent]): void


## [@frameworks/GramJs.ts]

TelegramFramework#
TelegramFramework#(...)
TelegramFramework#commands -> KeyValue<@Key -> string, @Value -> Command>
```
- [x] Membuat table dalam database MySQL untuk menyimpan data file yang telah terdownload
```
Table `files` schema:

id -> INT INCREMENT NOT NULL
file_id -> UNSIGNED BIGINT NOT NULL
chat_id -> UNSIGNED INT NOT NULL
created_at -> DATETIME NOT NULL
updated_at -> DATETIME NOT NULL
```

**Comment by hansputera** [comment]
Priorities:
1. command handler
2. mysql table
3. query resolver

**Comment by hansputera** [comment]
Lupa nambahin:
- [ ] Menambahkan args, flags parser
```
Karena di [@structures/Message.ts] udah dipisah command namenya jadi,
kita sisa ambil aja sisanya sebagai array.

Contoh:

pure text: "/cari boruto --minimalist"
preprocess: "boruto --minimalist"

Data diatas udah ada untuk saat ini, jadi sisa di proses lagi aja menjadi flags, dan args.
Contoh flags (--minimalist, --red, --green, --blue)

Flags, dan args ini juga akan saling berkaitan, karena dalam args juga ada tipe option.

Option itu berupa seperti ini bentuknya (--key=value),
sehingga dapatnya juga harus dari flags, dan dimasukan ke dalam args -> { name: key, value: value }

-------------------------------------
Kalau args sendiri, nanti juga ada parsing untuk tipe arg, misal integer,
maka value yang akan diberikan kepada Command juga hasil value dari argnya adalah number
```

**Comment by hansputera** [comment]
Semua task yang terdaftar sudah terlaksana, hal yang perlu ditambahkan untuk User Experience:

1. Video stream download progress tracker
2. Video stream download mirror selection (seleksi mirror web stream video melalui button)
3. Increase video stream download speed
4. Add "help" or "menu" command to show available commands
